name: Build and upload bar file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-bar-file
        path: target/my-bar-file.bar
