name: Build and upload bar file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: |
        mvn clean package
        ls target/
        # Check the generated .bar file name, and update the path parameter accordingly

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-bar-file
        path: target/my-bar-file-1.0-SNAPSHOT.bar
